### ISSUE TITLE
demo运行报Error: RawTaosError(TaosError { code: RpcFqdnError, err: "" })

### ISSUE THREAD

**Issue by rmokerone** [taosdata/libtaos-rs#11]
```
cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/test_libtaos`
Error: RawTaosError(TaosError { code: RpcFqdnError, err: "" })
```
报这个错误，IP也已经设置对了，且命令行运行taos是正常的。

**Comment by zitsen** [comment]
FQDN error 请检查如下设置：

1. ping <server hostname>, 检查是否成功
2. 在 cargo 运行机器上运行 taos 客户端
3. 在 taos shell 客户端中执行以下命令，测试是否成功：

       create database test1;
       use test1;
       create table tb1 (ts timestamp, v int);
       insert into tb1 values(now, 1);

**Comment by rmokerone** [comment]
设置都是正确的
我知道是什么原因了，我是在docker里面运行的taos服务，和这个issuse一样的。https://github.com/taosdata/TDengine/issues/3427
