### ISSUE TITLE
2.4以后版本的rest需要指定db，但是rest方面代码没有带这个参数

### ISSUE THREAD

**Issue by jamesdzhang** [taosdata/libtaos-rs#12]
2.4以后版本的rest需要指定db，但是rest方面代码没有带这个参数。
报错：
Error: RawTaosError(TaosError { code: TscDbNotSelected, err: "Database not specified or available" })

**Comment by zitsen** [comment]
You should use `db.stb` style to explicitly apply db name in sql.

We'll consider a more convenient way to do this next few weeks.
