### ISSUE TITLE
The original version does not support NULL values

### ISSUE THREAD

**Issue by jamesdzhang** [taosdata/libtaos-rs#13]
rest.rs Line54 【value_to_field】方法是用于map值和meta信息的，但是demo里的insert字段为null值，会按col是int来强行map；
建议在match逻辑前，判断是否是null，如果是直接返回null的field。

**Comment by zitsen** [comment]
thanks @jamesdzhang . The rest client hasn't been tested well, we are focusing on applying new features to Rust connector currently, but we'll take some time on the issue, sorry for the disposition. If you want to fix by now, you can fix it in the code and open a pr to the project, which is we are appreciating for.
