### ISSUE TITLE
Exception safety issue in `stmt.rs`

### ISSUE THREAD

**Issue by lizhuohua** [taosdata/libtaos-rs#17]
In function `bind`, all the `BindParam` are freed by `BindParam::free()`:

https://github.com/taosdata/libtaos-rs/blob/a8a46cf5a0589aaf3881f942def43484ba861aaa/src/stmt.rs#L66

However, there is a potential memory leak because errors may happen, thus `bind` returns before calling `free`.

https://github.com/taosdata/libtaos-rs/blob/a8a46cf5a0589aaf3881f942def43484ba861aaa/src/stmt.rs#L61-L63

Probably `free` should be implemented as an automatic destructor through the `Drop` trait so that Rust can automatically deallocate memory.

**Comment by fenghua1997** [comment]
Thanks for the feedback,  you can submit a PR

**Comment by zitsen** [comment]
Thanks, will fix this soon.
