### ISSUE TITLE
Async APIs for Taos are not async

### ISSUE THREAD

**Issue by sunng87** [taosdata/libtaos-rs#2]
First, thank you for this library. We are investigating it for our data proxy.

If I understand correctly, the `Taos::query` API defined in `client.rs` is not async. 
https://github.com/taosdata/libtaos-rs/blob/main/src/client.rs#L111

Marking it as async may result in abuse of these APIs in async runtime like tokio. 

Did I miss something or if there is any particular design for this?

**Comment by zitsen** [comment]
`taos_query` API use `taos_query_a` at thtask::spawn_blockinge low-level and just wait for the result. I'm not able to figure out if it make difference here use `tokio::task::spawn_blocking` or not, but it is designed to be compatible with restful API with `reqwest` crate by just a feature switch.

In next version, I'm thinking of that to use a synchronous-default version and use async/await as a feature to provides a more C compatible API. So, if you have any questions about the crate, please let me known, thanks very much.

Close this issue, and we want to be in-touch with you. Contact me as `zitsen` with WeChat, or the same id with Twitter.
